# Generated by Django 6.0.6 on 2026-07-04 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('RECEIVED', 'Order Received'), ('PRODUCTION', 'In Production'), ('DISPATCHED', 'Dispatched / In Transit'), ('DELIVERED', 'Delivered')], default='RECEIVED', max_length=20)),
                ('tracking_number', models.CharField(blank=True, help_text='e.g. TRK-GRE-1004', max_length=100, null=True)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='quotes.quote')),
            ],
        ),
    ]
